version: '3.4'

services:
  web:
    environment:
      - Auth=${TT_WEB_AUTH}
      - ApiUrl=${TT_WEB_APIURL}
      - UserId=${TT_WEB_USERID}
      - ApiUrlShoppingCart=${TT_WEB_APISHOPPINGCART}
    ports:
      - "5100:80"   
