name: End to End

on:
  push:
    branches:
    - main
    - actions
  workflow_dispatch:  # manual trigger

env:
  tf_version: 0.14.3
  tf_dir: Deploy/Terraform/environment
  web_app_name: cdtailwindgha
  web_app_rg_name: cd-ghactions-demo
  slot_name: DEV

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies in client app
      working-directory: Source/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build and publish with dotnet
      working-directory: Source/Tailwind.Traders.Web
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o publish --runtime linux-x64 --self-contained false

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: Source/Tailwind.Traders.Web/publish
    
  dev_infra_plan:
    needs: build
    runs-on: ubuntu-latest
    env:
      env_name: DEV
    defaults:
      run:
        working-directory: ${{ env.tf_dir }}
    environment:
      name: DEV
    steps:
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Authentication for TF
      uses: Azure/cli@v1
      with:
        inlineScript: | 
          echo "ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(az account show --query="user.name" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq '.clientSecret' -r <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)" >> $GITHUB_ENV

    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Init TF
      run: terraform init --backend-config="key=${{ env.env_name }}.terraform.tfstate"

    - name: TF Plan
      run: terraform plan -no-color -var-file=terraform.${{ env.env_name }}.tfvars -out=out.plan
    
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.env_name }}-tf-plan
        path: ${{ github.workspace }}/${{ env.tf_dir }}/out.plan
    
    - name: Azure logout
      run: az logout

  dev_infra_apply:
    needs: dev_infra_plan
    runs-on: ubuntu-latest
    env:
      env_name: DEV
    defaults:
      run:
        working-directory: ${{ env.tf_dir }}
    environment:
      name: DEV
    outputs:
      webapp_url: ${{ steps.get_webapp_url.outputs.stdout }}
    steps:
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Authentication for TF
      uses: Azure/cli@v1
      with:
        inlineScript: | 
          echo "ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(az account show --query="user.name" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq '.clientSecret' -r <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)" >> $GITHUB_ENV

    - name: Download plan
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.env_name }}-tf-plan
        path: ${{ github.workspace }}/${{ env.tf_dir }}
    
    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Init TF
      run: terraform init --backend-config="key=${{ env.env_name }}.terraform.tfstate"

    - name: TF Apply
      run: terraform apply -no-color -input=false -auto-approve out.plan

    - id: get_webapp_url
      name: Output web app URL
      run: terraform output -raw slotURL
    
    - name: Azure logout
      run: az logout

  dev_deploy:
    needs: dev_infra_apply
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: ${{ needs.dev_infra_apply.outputs.webapp_url }}
    steps:
    - name: Echo url from previous stage
      run: echo "Got [${{ needs.dev_infra_apply.outputs.webapp_url }}] from previous job"

    - name: Download site package
      uses: actions/download-artifact@v2
      with:
        name: site
        path: ${{ github.workspace }}/site
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: List files
      run: ls -la ${{ github.workspace }}/site

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.web_app_name }}
        slot-name: ${{ env.slot_name }}
        package: ${{ github.workspace }}/site
    
    - name: Echo url from deployment
      run: echo "Got [${{ steps.deploywebapp.outputs.webapp-url }}] from previous step"

    - name: Azure logout
      run: az logout

  prod_infra_plan:
    needs: dev_deploy
    runs-on: ubuntu-latest
    env:
      env_name: PROD
    defaults:
      run:
        working-directory: ${{ env.tf_dir }}
    environment:
      name: PROD
    steps:
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Authentication for TF
      uses: Azure/cli@v1
      with:
        inlineScript: | 
          echo "ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(az account show --query="user.name" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq '.clientSecret' -r <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)" >> $GITHUB_ENV

    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Init TF
      run: terraform init --backend-config="key=${{ env.env_name }}.terraform.tfstate"

    - name: TF Plan
      run: terraform plan -no-color -var-file=terraform.${{ env.env_name }}.tfvars -out=out.plan
    
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.env_name }}-tf-plan
        path: ${{ github.workspace }}/${{ env.tf_dir }}/out.plan
    
    - name: Azure logout
      run: az logout

  prod_infra_apply:
    needs: prod_infra_plan
    runs-on: ubuntu-latest
    env:
      env_name: PROD
    defaults:
      run:
        working-directory: ${{ env.tf_dir }}
    environment:
      name: PROD
    outputs:
      webapp_url: ${{ steps.get_webapp_url.outputs.stdout }}
    steps:
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Authentication for TF
      uses: Azure/cli@v1
      with:
        inlineScript: | 
          echo "ARM_SUBSCRIPTION_ID=$(az account show --query="id" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=$(az account show --query="user.name" -o tsv)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq '.clientSecret' -r <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(az account show --query="tenantId" -o tsv)" >> $GITHUB_ENV

    - name: Download plan
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.env_name }}-tf-plan
        path: ${{ github.workspace }}/${{ env.tf_dir }}
    
    - name: Install TF
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Init TF
      run: terraform init --backend-config="key=${{ env.env_name }}.terraform.tfstate"

    - name: TF Apply
      run: terraform apply -no-color -input=false -auto-approve out.plan

    - id: get_webapp_url
      name: Output web app URL
      run: terraform output -raw webappURL
    
    - name: Azure logout
      run: az logout

  prod_deploy:
    needs: prod_infra_apply
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: ${{ steps.deploywebapp.outputs.webapp-url }}
    steps:
    - name: Echo url from previous stage
      run: echo "Got [${{ needs.dev_infra_apply.outputs.webapp_url }}] from previous job"

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Swap slots
      run: az webapp slot swap -g ${{ env.web_app_rg_name }} -n ${{ env.web_app_name }} -s ${{ env.slot_name }}

    - name: Azure logout
      run: az logout