name: Web regular AppService

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Install dependencies in client app
      working-directory: Source/Tailwind.Traders.Web/ClientApp
      run: npm install

    - name: Build with dotnet
      working-directory: Source/Tailwind.Traders.Web
      run: dotnet build --configuration Release
    - name: dotnet publish
      working-directory: Source/Tailwind.Traders.Web
      run: |
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Source/Tailwind.Traders.Web

    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ secrets.WEBAPP_APPSERVICE_NAME }}
        app-settings-json: '${{ secrets.WEBAPP_APP_SETTINGS }}'


    - name: Run Azure webapp deploy action
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ secrets.WEBAPP_APPSERVICE_NAME }}
        package: ${{env.DOTNET_ROOT}}/Source/Tailwind.Traders.Web

    - name: Azure logout
      run: |
        az logout